# Generated by Django 3.1.7 on 2021-03-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbers',
            name='fname',
            field=models.CharField(default='Pratik', max_length=200),
        ),
        migrations.AddField(
            model_name='numbers',
            name='lname',
            field=models.CharField(default='Pratik', max_length=200),
        ),
    ]
